<?php
namespace JetApplicationModule\Projects\Admin;

use JetApplication\Project as Project;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Project $item ) use ( $router ) {
		if( ( $delete_uri = $router->action('delete')->URI( $item->getCode() ) ) ):
			echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
			echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		endif;
		if( ( $edit_uri = $router->action('edit')->URI( $item->getCode() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:200px;' );

$grid->getColumn( 'code' )->addCustomCssStyle( 'width:120px;' );

$grid->getColumn( 'code' )->setRenderer(
	function( Project $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getCode();?></a>
		<?php
	}
);

$grid->getColumn( 'connection_type' )->setRenderer(
	function( Project $item ) use ( $router ) {
		echo $item->getConnectionTypeTitle();
	}
);

$grid->getColumn( 'connection_host' )->setRenderer(
	function( Project $item ) use ( $router ) {
		echo $item->getConnectionHost();
	}
);


$grid->getColumn( 'name' )->setRenderer(
	function( Project $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->getCode() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getName();?></a>
		<?php
	}
);

$grid->getColumn( 'notes' )->setRenderer(
	function( Project $item ) use ( $router ) {
		echo nl2br( $item->getNotes() );
	}
);

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( 'Create a new Project' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=$filter_form->field('search')->input()?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
