<?php
namespace JetApplicationModule\Admin\Projects;

use JetApplication\Project as Project;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var Project       $project
 */
$project = $this->getRaw( 'project' );
$router = $this->getController()->getControllerRouter();

?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( 'Do you really want to delete this project?' );?>
				<br/>
				<a href="<?=$router->action('edit')->URI( $project->getCode() );?>"
				   style="font-weight: bolder;font-size: 20px;"><?=$project->getName();?> (<?=$project->getName();?>)</a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack() ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
