<?php
namespace JetApplicationModule\Projects\Deployer;

use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\UI_messages;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller;
 */

$controller = $this->controller;

$current_project = $controller->getCurrentProject();
$current_deployment = $controller->getCurrentDeployment();

require __DIR__.'/../lj/head.phtml';
	?>
	<br><br>
	<?=UI_messages::createDanger(Tr::_('Error during deployment preparation. Details below.'))->setCloseable(false)?>
	<br>
	
	<?php if($current_deployment->deploymentPrepareAllowed()): ?>
	<?=UI::button(Tr::_('Try again'))->setUrl(MVC::getPage()->getURL(GET_params: [
		'project' => $current_project->getCode(),
		'deployment' => $current_deployment->getId(),
		'action' => 'prepare_again'
	]))->setClass(UI_button::CLASS_PRIMARY)?>
	<?php endif; ?>
	<br>
	<hr>

	<h3><?=Tr::_('Log of deployment preparation')?></h3>
	<?=$current_deployment->getPrepareLog();?>
	
<?php
require __DIR__.'/../lj/foot.phtml';
