<?php
namespace JetApplicationModule\Projects\Deployer;

use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Deployment;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller;
 */

$controller = $this->controller;

$current_project = $controller->getCurrentProject();
$current_deployment = $controller->getCurrentDeployment();

$selected_files = $current_deployment->getSelectedFiles();

$active_mode = $current_deployment->getState()==Deployment::STATE_PREPARATION_DONE;

$diff = $active_mode ? $current_deployment->getDiff() : null;

if(!$selected_files) {
	return;
}

asort($selected_files);
?>
<h2><?=Tr::_('Selected files')?></h2>

<table class="table table-striped">
	<?php foreach($selected_files as $file): ?>
	<tr>
		<td style="width: 100px;">
		<?php if($diff?->fileIsChanged($file)): ?>
			<a href="<?=MVC::getPage()->getURL(GET_params: [
					'project' => $current_project->getCode(),
					'deployment' => $current_deployment->getId(),
					'action' => 'compare_file',
					'file' => $file
				])?>" target="_blank"><?=Tr::_('Compare')?></a>
		<?php endif; ?>
		</td>
		<td>
			<?php if($active_mode): ?>
				<?=UI::icon('trash')->addJsAction('onclick',"unselectFile('$file')" )?>
			<?php endif; ?>
		</td>
		<td><?=$file?></td>
	</tr>
	<?php endforeach; ?>
</table>

<br><br><br>
<?php if($active_mode): ?>
	<?=UI::button(Tr::_('Start deployment'))
		->setClass(UI_button::CLASS_SUCCESS)
		->setIcon('')
		->setUrl(MVC::getPage()->getURL(GET_params: [
			'project'=> $current_project->getCode(),
			'deployment' => $current_deployment->getId(),
			'action' => 'deployment_start_show'
		]))
		->addJsAction('onclick', "return confirm('".addslashes(Tr::_('Do you really want to start deployment?'))."');")
		?>
<br><br><br>
<?php endif; ?>
