<?php
namespace JetApplicationModule\Projects\Deployer;

use Jet\Locale;
use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Deployment;


/**
 * @var MVC_View   $this
 * @var Controller_Main $controller;
 */

$controller = $this->controller;

$current_project = $controller->getCurrentProject();
$current_deployment = $controller->getCurrentDeployment();


$deleteBtn = function( Deployment $deployment ) use ($current_project) {
	if(!$deployment->deleteDeploymentAllowed()) {
		return;
	}
	?><a
		href="<?=MVC::getPage()->getURL(
		GET_params: [
			'project'=>$current_project->getCode(),
			'deployment' => $deployment->getId(),
			'action' => 'delete_deployment',
		])?>"
		onclick="return confirm('<?=Tr::_('Do you really want do delete this deployment?')?>')"
		class="text-danger"
	><?=UI::icon('trash')?></a><?php
};

$deploymentDeleted = function( Deployment $deployment ) {
	?>
	<small>
	<span class="badge badge-danger"><?=Tr::_('Deleted')?></span>
	<br>
	<?=Locale::dateAndTime( $deployment->getDeletedDateTime() ) ?><br>
	<?=$deployment->getDeletedByUserName()?> (<?=$deployment->getDeletedByUserId()?>)
	</small>
	<?php
};

$deploymentInfo = function( Deployment $deployment ) {
	?>
	<small>
		<?=$deployment->getUserName()?><br>
		<?=Locale::dateAndTime( $deployment->getStartDateTime() )?><br>
		<?=$deployment->getStateLabel()?>
		
		<?php if($deployment->getRollbackState()): ?>
			<br>
			<?=$deployment->getRollbackStateLabel()?>
		<?php endif; ?>
	</small>
	<?php
};

$deploymentLink = function( Deployment $deployment ) use ($current_project) {
	?>
	<a class="mb-1" href="<?=MVC::getPage()->getURL(GET_params: [
		'project' => $current_project->getCode(),
		'deployment' => $deployment->getId()
	])?>"><?=$deployment->getId()?></a>
	<?php
};

$deploymentSelected = function( Deployment $deployment ) use ($current_project) {
	?><b><?=$deployment->getId()?></b><?php
};
?>
<div class="row justify-content-center h-100">
	<div class="col-md-2 hidden-md-down bg-light">
		<?php if($current_project): ?>
		<br>
		<h5><?=Tr::_('Deployments')?>
			<?php if($current_project->deploymentPrepareAllowed()): ?>
			<?=UI::button_create(Tr::_('Start new'))->setUrl(
				MVC::getPage()->getURL(
					GET_params: [
						'project'=>$current_project->getCode(),
						'action' => 'start_new_deployment'
					])
			)
				->setSize(UI_button::SIZE_EXTRA_SMALL)
				->setClass(UI_button::CLASS_PRIMARY)
			?>
			<?php endif; ?>
		</h5>
		
		<ul class="list-group">
			<?php foreach($current_project->getDeployments() as $deployment):
					if($deployment->getDeleted()):
						if($deployment->getId()==$current_deployment?->getId()):
							?>
							<li class="list-group-item flex-column active" style="opacity: 0.3">
								<div class="d-flex w-100 justify-content-between">
									<div  class="mb-1">
										<?php $deploymentSelected( $deployment ) ?>
										<?php $deploymentDeleted($deployment); ?>
									</div>
									<?php $deploymentInfo($deployment) ?>
								</div>

							</li>
						<?php
						else:
							?>
							<li class="list-group-item flex-column" style="opacity: 0.3">
								<div class="d-flex w-100 justify-content-between">
									<div  class="mb-1">
										<?php $deploymentLink( $deployment ) ?>
										<?php $deploymentDeleted($deployment); ?>
									</div>
									<?php $deploymentInfo($deployment) ?>
								</div>
							</li>
						<?php
						endif;
					else:
						if($deployment->getId()==$current_deployment?->getId()):
							?>
							<li class="list-group-item flex-column active">
								<div class="d-flex w-100 justify-content-between">
									<div class="mb-1">
										<?php $deploymentSelected( $deployment ) ?>
										<br>
										<br>
										<?=$deleteBtn($deployment)?>
									</div>
									<?php $deploymentInfo($deployment) ?>
								</div>

							</li>
						<?php
						else:
							?>
							<li class="list-group-item flex-column">
								<div class="d-flex w-100 justify-content-between">
									<div class="mb-1">
										<?php $deploymentLink($deployment) ?>
										<br><br>
										<?php $deleteBtn( $deployment ); ?>
									</div>
									<?php $deploymentInfo($deployment) ?>
								</div>
							</li>
						<?php
						endif;
					endif;
				endforeach; ?>
		</ul>
		<?php endif; ?>
	</div>
	<div class="col-10">
