<?php
namespace JetApplicationModule\Projects\Deployer;

use Jet\Locale;
use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetApplication\Project;

/**
 * @var MVC_View   $this
 * @var Controller_Main $controller;
 */

$controller = $this->controller;

$current_project = $controller->getCurrentProject();
$current_deployment = $controller->getCurrentDeployment();
?>
<div class="row justify-content-center h-100">
	<div class="col-md-2 hidden-md-down bg-light">
		<?php if($current_project): ?>
		<br>
		<h5><?=Tr::_('Deployments')?>
			
			<?=UI::button_create(Tr::_('Start new'))->setUrl(
				MVC::getPage()->getURL(
					GET_params: [
						'project'=>$current_project->getCode(),
						'action' => 'start_new_deployment'
					])
			)
				->setSize(UI_button::SIZE_EXTRA_SMALL)
				->setClass(UI_button::CLASS_PRIMARY)
			?>
		</h5>
		
		<ul class="list-group">
			<?php foreach($current_project->getDeployments() as $deployment):
					if($deployment->getId()==$current_deployment?->getId()):
						?>
						<li class="list-group-item flex-column active">
							<div class="d-flex w-100 justify-content-between">
								<b class="mb-1"><?=$deployment->getId()?></b>
								<small>
									<?=$deployment->getUserName()?><br>
									<?=Locale::dateAndTime( $deployment->getStartDateTime() )?><br>
									<?=$deployment->getStateLabel()?>
								</small>
							</div>
							
						</li>
						<?php
					else:
						?>
						<li class="list-group-item flex-column">
							<div class="d-flex w-100 justify-content-between">
								<a href="<?=MVC::getPage()->getURL(GET_params: [
									'project' => $current_project->getCode(),
									'deployment' => $deployment->getId()
								])?>"><?=$deployment->getId()?></a>
								<small>
									<?=$deployment->getUserName()?><br>
									<?=Locale::dateAndTime( $deployment->getStartDateTime() )?><br>
									<?=$deployment->getStateLabel()?>
								</small>
							</div>
						</li>
						<?php
					endif;
				endforeach; ?>
		</ul>
		<?php endif; ?>
	</div>
	<div class="col-10">
