<?php
namespace JetApplicationModule\Deployer\Projects;

use Jet\MVC;
use Jet\MVC_View;
use Jet\Tr;
use JetApplication\Project;

/**
 * @var MVC_View   $this
 */
?>

<div class="col-12">
	<br>
	<br>
	<h5><?=Tr::_('Select project')?></h5>
	<ul class="list-group">
		
		<?php foreach(Project::getListOfCurrentUser() as $project ):
			?>
			<li class="list-group-item">
				<a href="<?=MVC::getPage()->getURL(GET_params: ['project'=>$project->getCode()])?>" style="font-weight: bolder;font-size: 1.5rem"><?=$project->getName()?></a>
				<br>
				<span class="badge badge-primary"><?=$project->getConnectionHost()?></span>
				<span class="badge badge-secondary"><?=$project->getConnectionTypeTitle()?></span>
				<br>
				<?=nl2br($project->getNotes())?>
			</li>
		<br>
		<?php
		endforeach; ?>
	</ul>
</div>
